name: "ipaddress"

version: 0.2.11
description: >-
  ipaddress handles ipv4 and ipv6
homepage: https://github.com/mabels/ipaddress
repository: https://github.com/mabels/ipaddress
issue_tracker: https://github.com/mabels/ipaddress/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  test: '>=1.26.2'
dependencies:
  result_monad: ^2.3.2
